### ISSUE TITLE
SystemJS and Angular modules - Looking for the right design pattern

### ISSUE THREAD

**Issue by molekilla** [edgarSucre/ifrit#1]
Edgar

This is the same pattern I found everywhere.

edgarSucre/ifrit/blob/master/app/main/main-module.ts#L2

But I want to load `app` first, then app.controllers, etc... with angular.module. What SystemJS does is to load async all imports then it continues executing app.js and so on.

What I did in molekilla/rutha-2016 was to add the canonical name (eg app.controllers.serviceName) as module name

https://github.com/molekilla/rutha-2016/blob/angular-training-promises/src/app/common/services/UserService.ts#L61-L62

I found some people avoiding SystemJS and others use some kind of Promise chain to load app module first then internal modules but really lost until further sample code from Angular.io, which I'm using as guide for Angular 1 + Typescript in rutha-2016

References
1 - http://blog.rangle.io/unittests/
2 - http://stackoverflow.com/questions/31081300/how-to-use-systemjs-to-bundle-angular-typescript-with-internal-modules
3 - Promise chain example http://stackoverflow.com/questions/32623175/lazy-loading-angular-module-with-es6-and-systemjs-import
4 - Lookfirst is using OCLazyLoad https://egghead.io/lessons/angularjs-simple-lazy-loaded-angular-module-syntax-with-oclazyload

**Comment by edgarSucre** [comment]
So, you want to declare module dependencies in the component rather than the module, that way you don't need to import the file to the module, and imported just when needed?

That should work, I'll try that approach, and get back to you.

**Comment by edgarSucre** [comment]
We need to discuss this further. I'd like to see a working example trying to load modules only when needed. With the classic approach all files are loaded because of the module dependency chain.

**Comment by molekilla** [comment]
It means then lazy load is the way to use it (as found in the lookfirst
seed)

**Comment by molekilla** [comment]
I found this video for Ionic and Typescript: http://blog.ionic.io/ionic-and-typescript-part-3/

I liked how you could have a "module table" like the routes table you do for each section.

You could have

/app
   /services
     MyServiceA.ts
     MyServiceB.ts
     ServiceModule.ts

```
import {MyServiceA} from './MyServiceA'
angular.module('app.services', [])
.service('MyServiceA', MyServiceA)
// ...
```
